package io.fritz2

val fritz_version = "0.5"

plugins {
    id("org.jetbrains.kotlin.multiplatform")
    id("org.jetbrains.kotlin.kapt")
}

repositories {
    jcenter()
}

kotlin {
    kotlin {
        jvm()
        js().browser()

        sourceSets {
            val commonMain by getting {
                dependencies {
                    implementation(kotlin("stdlib"))
                    implementation("io.fritz2:core:$fritz_version")

                    configurations.get("kapt").dependencies.add(compileOnly("io.fritz2:lenses-annotation-processor:$fritz_version"))

                    tasks.getByName("compileKotlinJs").dependsOn("kaptKotlinJvm")

                    tasks.getByName("clean") {
                        doLast {
                            delete("src/commonGenerated")
                        }
                    }
                }
            }
            val commonGenerated by creating {
                dependsOn(commonMain)
                kotlin.srcDir("src/commonGenerated")
            }
            val jvmMain by getting {
                dependsOn(commonGenerated)
                dependencies {
                }
            }
            val jsMain by getting {
                dependsOn(commonGenerated)
                dependencies {
                }
            }

        }
    }
}
